### ISSUE TITLE
Reuse branch for Nightly PRs?

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/relbot#32]
Now that taskcluster is wonky the bot opened a PR for every Nightly version and we have a bunch of them. I wonder if we could reuse the same branch (afaik that's what we did with MickeyMoz) or have some other mechanism to avoid having a bunch of concurrent PRs.

**Comment by st3fan** [comment]
Couple of options:

 - Nothing: keep generating unique PRs and branches. We would manually close old ones.
 - Auto close old branches: if for some reason we skipped a previous PR, the relbot could close them. It is not very difficult to look at previous PRs and close those that are not relevant anymore.
 - Update existing PR: if we skip a PR, we could re-use it. It is easy to push another commit to it, and we can also update the title so that it reflects the correct GV version.

I think I prefer the latter - but one thing that is tricky there is timing and concurrent access to the PR. We don't want to mess with a PR while it is being landed by Mergify for example. I'll have to sleep on that a bit longer to understand how to avoid that.

**Comment by st3fan** [comment]
I updated this to _re-use branch for *Nightly* PRs_ - I think that is a good starting point and the place where updates happen most frequently with the highest chance of them piling up.

**Comment by st3fan** [comment]
This happened over the weekend:

```
2020-12-30 11:13:20.357383 Current GV Nightly version in A-C is 86.0.20201225095506
2020-12-30 11:13:21.451538 Latest GV Nightly version available is 86.0.20201229095620
2020-12-30 11:13:21.451565 We should update A-C master with GV Nightly 86.0.20201229095620
2020-12-30 11:13:21.560474 The PR branch relbot/ac-master already exists. Exiting.
```

**Comment by st3fan** [comment]
> I guess one thing we could do is see if the GV update is newer and then if no changes have been added to that PR, we re-use it and simply try again with that newer GV. There no guarantee that this will always unbreak things though, but at least we try. (edited)

**Comment by rvandermeulen** [comment]
I don't think we need to do this. Mergify deletes the branch when the PR merges, so it's only a factor when we have to close out a PR and manually delete. That's rare enough that I don't think it's something to be concerned with fixing.
